### PR TITLE
Add GitHub Action for charts

### PR DESCRIPTION
**Pull request by djjudas21**

### CODE REVIEW

**Review by nitnelave — APPROVED** [review]

**Comment by nitnelave** [comment]
Checks seem to pass! Can you merge yourself? Do you have the permission?

**Comment by djjudas21** [comment]
Looks like I do!

**Comment by djjudas21** [comment]
One thing for you to check please, in the repository settings, can you ensure GitHub Pages is enabled, and pointing at the `gh-pages` branch?

Basically follow [these instructions](https://helm.sh/docs/topics/chart_repository/#github-pages-example) and pick a URL that you're happy with. I suggest https://lldap.github.io/charts which also means you can host other content on https://lldap.github.io in the future if you wish to.

**Comment by nitnelave** [comment]
I'll have a look when I can, I won't have access to a computer for a few days.

**Pull request merged**
